### ISSUE TITLE
Minicolors renders nicely, but isn't interactive - what's wrong?

### ISSUE THREAD

**Issue by tomsoderlund** [kaihenzler/angular-minicolors#12]
I'm trying to integrate `angular-minicolors` into another directive in a larger AngularJS 1.3 app.

My template code looks like:

	template: '<div class="color-picker">'
				+ '<div ng-repeat="colorValue in colors" class="color-box {{colorValue}}" ng-class="{selected: colorValue == ngModel, transparent: colorValue == \'transparent\'}" ng-click="selectColor(colorValue)">'
					+ '<span class="icon {{icon}}" style="color: {{colorValue}}"></span>'
					+ '<div class="modify-color">'
						+ '<label for="inline">Inline: {{color.inline}}</label><br>'
						+ '<input minicolors="miniColorConfig" type="hidden" ng-model="tempColor">'
					+ '</div>'
				+ '</div>'
			+ '</div>',

My config looks like:

	$scope.miniColorConfig = {
		theme: 'weld',
		position: 'top left',
		defaultValue: '',
		animationSpeed: 50,
		animationEasing: 'swing',
		change: null,
		changeDelay: 0,
		control: 'wheel',
		hide: null,
		hideSpeed: 100,
		inline: true,
		letterCase: 'lowercase',
		opacity: false,
		show: null,
		showSpeed: 100
	};

It renders a nice wheel with the correct color indicated, but I can't change the color. The JavaScript console is blank, no errors. Any ideas?

**Comment by kaihenzler** [comment]
@tomsoderlund is this issue resolved for you?

**Comment by tomsoderlund** [comment]
Yes! Can't remember how though - it was a while ago :-)
