### ISSUE TITLE
o.minicolors is not a function

### ISSUE THREAD

**Issue by Quagh** [kaihenzler/angular-minicolors#13]
Just did a default install, but keep getting this error. Seems the `minicolors` method doesn't exist when it tries to execute it on the element trough `element.minicolors()`. Did a few debug console logs and it couldn't get past `element.minicolors('destroy');`

In my view:
`<input type="text" minicolors ng-model="derp" />`

In my controller:
`$scope.derp = '#FF0000';`

Files are loaded in the following order:
1. Angular, jQuery, etc
2. jQuery Minicolors
3. Angular Minicolors directive

Used versions (tried a few):
- jQuery 1.11.2, v2.x.x, etc
- jquery-minicolors 2.1.7
- angular-minicolors 0.0.5

**Comment by kaihenzler** [comment]
Hey there,
I didn't Test anyrhing But just read The email, You have to load JQuery First And angular afterwards. Angular Uses jqLite if IT doesn't Find JQuery. this might be the Cause of your problem.
Could you Test if IT Works if you load JQuery First?

Greetings, Kai

**Comment by Quagh** [comment]
Yeeeep, that was it. Thanks!

Just to notify you, I know have the issue where minicolors deletes the parent of the input div (https://github.com/kaihenzler/angular-minicolors/issues/5).
