### ISSUE TITLE
Color dropdown not reinitializing when settings change

### ISSUE THREAD

**Issue by mcurland** [kaihenzler/angular-minicolors#21]
Dynamically changing settings is not working. The watch is triggering correctly, but there is no .minicolors class on the element.

        if(element.hasClass('minicolors')) {
          element.minicolors('destroy');
        }
needs to be:
        if(element.hasClass('minicolors-input')) {
          element.minicolors('destroy');
        }
This didn't seem worth a pull request.

Nice little wrapper. Thanks.

**Comment by kaihenzler** [comment]
Thanks for pointing out the issue
