### ISSUE TITLE
form-group div is getting removed

### ISSUE THREAD

**Issue by newmanw** [kaihenzler/angular-minicolors#23]
I start with this html:

```html
          <div class="row">
            <div class="col-sm-12>
              <label class="control-label" for="poop">Some Color</label>
              <div class="form-group">
                <input id="poop" minicolors="minicolorSettings" class="form-control" type="text" ng-model="someColor">
              </div>
            </div>
          </div>
```

And the <div class="form-group"> is removed from the html.

**Comment by newmanw** [comment]
Note:  Since the directive seems to mess with the parent div that has the form group I was able to workaround this issue by adding an extra div around the input:

```html
              <div class="form-group">
                <div><input id="poop" minicolors="minicolorSettings" class="form-control" type="text" ng-model="someColor"></div>
              </div>
```

Still should probably be fixed at some point.

**Comment by newmanw** [comment]
Sorry, looks like this relates to #20 

However #20 is closed and says the docs are updated.  But the docs read:

```html
<div class="form-group">
  <label for="color-input" class="form-control">Color:</label>
  <input
    minicolors="customSettings"
    id="color-input"
    class="form-control"
    type="text"
    ng-model="input.color">
</div>
```

When I think they should read:
<div class="form-group">
  <label for="color-input" class="form-control">Color:</label>
  <div>
    <input
      minicolors="customSettings"
      id="color-input"
      class="form-control"
      type="text"
      ng-model="input.color">
  </div>
</div>
```

**Comment by kaihenzler** [comment]
@newmanw thanks for pointing that out. 
I will try to either update the demo page or to render the directive into a <div></div> template, which should fix this problem.

kind regards,
Kai

**Comment by newmanw** [comment]
@kaihenzler no worries and thanks.  Great directive!

**Comment by kaihenzler** [comment]
closing since it doesn't seem relevant anymore. reopen it if your still looking for a fix.
