### ISSUE TITLE
position attribute not working

### ISSUE THREAD

**Issue by happschinson** [kaihenzler/angular-minicolors#24]
whenever I add the "position" attribute to my custom settings object, angular-minicolos is not getting initialized anymore.

$scope.minicolors = {
      position: 'top right',
      theme: 'bootstrap'
    };

**Comment by kaihenzler** [comment]
Have you included the bootstrap css stylesheet? I'm not sure if it works without it.

If you have included it correctly, could you please post the complete snippet of html?

**Comment by kaihenzler** [comment]
@happschinson any updates?

**Comment by happschinson** [comment]
because we were in a hurry with our project we ended up using a different color library, I'm sorry :/

**Comment by kaihenzler** [comment]
Thanks anyways.
