### ISSUE TITLE
Binding, default value

### ISSUE THREAD

**Issue by bobmulder** [kaihenzler/angular-minicolors#27]
Hey,

The input is great, however, when I load my angular stuff with a default value it's not used by the minicolors. Please fix it because I need this awesome very hard!

Bob

**Comment by kaihenzler** [comment]
Hey there, first of all: Thank You!

Can you provide me with information about your angular version, jquery version and possibly with a Fiddle, that illustrates your issue. You can also take a look at the gh-pages where you can see a working example:
https://github.com/kaihenzler/angular-minicolors/blob/gh-pages/index.html

kind regards,
Kai

**Comment by bobmulder** [comment]
I'm sorry @kaihenzler, it was my fault. The problem was that the hex wasn't complete (it was missing the last character). Probably we should fix that...
