### ISSUE TITLE
Is there any way to change the size of the popover?

### ISSUE THREAD

**Issue by btelintelo** [kaihenzler/angular-minicolors#29]
When I change the size in css, it looks like the generated base 64 data is not changing??

**Comment by kaihenzler** [comment]
Hey there,

unfortunately I don't know a way on how to resize the popover.

the author of the jQuery plugin suggested the following:
https://github.com/claviska/jquery-minicolors/issues/160

I'm going to close the issue since it's not related to the angular-wrapper.

Thank you
