### ISSUE TITLE
How to reset colors 

### ISSUE THREAD

**Issue by saadbinakhlaq** [kaihenzler/angular-minicolors#40]
I have a form where I need to reset the color to be `nil` or `''`, I have an angular scope variable button_color, which I would like to reset to `''`, `''` is not a valid color so the reset color is not working. Is there a work around for this. I am unable to find it anywhere.

but according to this piece of code.
```
          if (isValidColor(color) && canSetValue()) {
            element.minicolors('value', color);
          }
```

**Comment by abdo-host** [comment]
what the answer ?

**Comment by kaihenzler** [comment]
as a workaround I can suggest that you change any value in the setting object. this forces the component to re-render.
Note: this solution is really really bad. I'm a bit ashamed that I'm even suggesting it...

```
$scope.yourConfigObject = {
   theme: 'bootstrap',
   position: 'top left',
   defaultValue: '',
   animationSpeed: 50,
   // further config options...
}

$scope.reset = function () {
   $scope.yourConfigObject.show = false; //force component to re-render
   $scope.yourColorValue = null // reset your value
   $scope.yourConfigObject.show = true; //reset the property so this reset-fn can work multiple times
}
```
